# Generated by Django 4.2.7 on 2025-06-07 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('user_action', 'Action utilisateur'), ('system_alert', 'Alerte système'), ('banner_request', 'Demande de bannière'), ('user_registration', 'Inscription utilisateur'), ('profile_change', 'Modification de profil'), ('content_moderation', 'Modération de contenu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
