# Generated by Django 4.2.7 on 2025-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Club de Voitures Américaines', max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('founder_info', models.TextField(blank=True, null=True, verbose_name='Informations sur le fondateur')),
                ('cofounder_info', models.TextField(blank=True, null=True, verbose_name='Informations sur le co-fondateur')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Information du Club',
                'verbose_name_plural': 'Informations du Club',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('event_date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('is_published', models.BooleanField(default=False, verbose_name='Est publié')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['event_date'],
            },
        ),
    ]
