# Generated by Django 4.2.7 on 2025-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('rasso', 'Rassemblement'), ('other', 'Autre')], default='other', max_length=20, verbose_name="Type d'événement"),
        ),
    ]
