# Generated by Django 4.2.7 on 2025-04-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer_back',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/', verbose_name='Flyer (verso)'),
        ),
        migrations.AddField(
            model_name='event',
            name='flyer_front',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/', verbose_name='Flyer (recto)'),
        ),
    ]
