# Generated by Django 4.2.7 on 2025-05-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productcolor_productsize_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='core.productcolor', verbose_name='Couleur associée'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='view_type',
            field=models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('left', 'Left Side'), ('right', 'Right Side'), ('detail', 'Detail'), ('other', 'Other')], default='other', max_length=10, verbose_name='Type de vue'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small(XS)'), ('S', 'Small(S)'), ('M', 'Medium(M)'), ('L', 'Large(L)'), ('XL', 'Extra Large(XL)'), ('XXL', '2X Large(2XL)'), ('XXXL', '3X Large(3XL)')], max_length=10),
        ),
    ]
