# Generated by Django 4.2.7 on 2025-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_approved',
            field=models.BooleanField(default=False, verbose_name='Bannière approuvée'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_color',
            field=models.CharField(blank=True, default='#2c3e50', max_length=20, null=True, verbose_name='Couleur de bannière'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Image de bannière'),
        ),
    ]
