# Generated by Django 4.2.7 on 2025-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
