# Generated by Django 4.2.7 on 2025-04-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='fa-comments', max_length=50, verbose_name='Icône FontAwesome')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie du forum',
                'verbose_name_plural': 'Catégories du forum',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('slug', models.SlugField(unique=True)),
                ('is_locked', models.BooleanField(default=False, verbose_name='Sujet verrouillé')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Sujet épinglé')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Sujet du forum',
                'verbose_name_plural': 'Sujets du forum',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_solution', models.BooleanField(default=False, verbose_name='Marqué comme solution')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumtopic', verbose_name='Sujet')),
            ],
            options={
                'verbose_name': 'Réponse du forum',
                'verbose_name_plural': 'Réponses du forum',
                'ordering': ['created_at'],
            },
        ),
    ]
